name: Bandit Security Scan

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        run: bandit -r /Users/mahimchoudhury/Documents/CS673/hello_world/helloworld-react-flask-devops # Replace with your code directory

      - name: Upload Bandit Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: bandit-report
          path: .bandit
